# theme: jekyll-theme-minimal
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Barnabas Robotics
email: class@barnabasrobotics.com
description: > # this means to ignore newlines until "baseurl:"
  Barnabas Robotics is a for-profit company that values giving more than receiving.  We strive to empower others through creating a sustainable business that brings great value to our partners and customers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lessons.barnabasrobotics.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: barnabasrobotic
github_username:  barnabasrobotics
facebook_username: barnabasrobotics
youtube_username: barnabasrobotics
instagram_username: barnabasrobotics
repository: poproar/barnabas-instructors-guide
version: 1.0.0

collections:
  lessons:
    layout: lesson
    output: true
  racerlessons:
    layout: lesson
    output: true

# Build settings

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-github-metadata

exclude:
  - README.
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CODE_OF_CONDUCT.md
  - tmp
  - vendor
  - .gitignore
  - .git
  - .c9
